name: Node Server Check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: server
        run: npm install

      - name: Start server
        working-directory: server
        run: |
          node server.js &
          sleep 5

      - name: Check Node process
        run: ps aux | grep node

      - name: Check port 5000
        run: ss -lntp | grep 5000

      - name: Test API
        run: curl http://localhost:5000/api/hello
