name: Run Backend

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: server
        run: npm install

      - name: Start Backend
        working-directory: server
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: 5000
        run: node server.js
